-- AlterTable
ALTER TABLE "File" ADD COLUMN     "createdById" INTEGER NOT NULL DEFAULT 1;

-- AddForeignKey
ALTER TABLE "File" ADD CONSTRAINT "File_createdById_fkey" FOREIGN KEY ("createdById") REFERENCES "User"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
